### ISSUE TITLE
Left or Right pose

### ISSUE THREAD

**Issue by msh-tuhin** [rs9000/ergonomics#3]
What would be the difference between the _get_body_angles_from_pose_right()_ and the _get_body_angles_from_pose_left()_ methods? And how to determine which one to use?

**Comment by rs9000** [comment]
The REBA method it mainly focuses on work postures, it is only designed to assess the right side and the left side of the body separately, and there is no method for combining scores to obtain a result for the whole body. [1]

You can choose based on your goals or just take the max score.

In this implementation the difference would be manly on upper arm, lower arm and wrist angles, since they are computed on one side of the body.

[1] https://nawo-solution.com/reba-method/
